"""
History Models — Persistent memory layer for AI intelligence and auditing.

Tables:
  BusinessEvent          — Episodic record of every meaningful business occurrence
  RecommendationHistory  — Archive of AI-generated recommendations
  DecisionHistory        — Tracks what the user did with each recommendation + outcome
"""

from datetime import datetime

from sqlalchemy import Column, DateTime, Float, Integer, JSON, String

from app.database import Base


class BusinessEvent(Base):
    """
    Records every meaningful business event as a timestamped episodic memory entry.

    Event types:
      TRANSACTION     — Sales, payments received/made
      COMPLAINT       — Customer complaints
      SUPPLIER_DELAY  — Supplier delivery issues
      PRICE_CHANGE    — Product price adjustments
      DOC_INGESTED_*  — Parsed document uploads
      INVENTORY_ALERT — Stock threshold breaches
      CUSTOM          — Operator-logged events
    """

    __tablename__ = "business_events"

    id = Column(Integer, primary_key=True, index=True)
    event_type = Column(String(50), nullable=False, index=True)
    description = Column(String(2000), nullable=False)
    explanation = Column(String(2000), nullable=True)
    severity = Column(String(20), default="INFO")         # INFO | WARNING | CRITICAL
    source = Column(String(50), default="system")         # system | user | ai | upload
    entity_type = Column(String(50), nullable=True)       # customer | supplier | product | invoice
    entity_id = Column(Integer, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    metadata_json = Column(JSON, nullable=True)

    @property
    def get_explanation(self) -> str:
        """Returns explanation if present, falling back to description."""
        return self.explanation or self.description or ""

    @property
    def get_related_entities(self) -> list:
        """Returns related_entities list from metadata_json if present, or constructs from entity_type/entity_id."""
        if self.metadata_json and isinstance(self.metadata_json, dict) and "related_entities" in self.metadata_json:
            return self.metadata_json["related_entities"]
        if self.entity_type and self.entity_id:
            return [{"entity_type": self.entity_type, "entity_id": self.entity_id}]
        return []



class RecommendationHistory(Base):
    """
    Archive of every AI recommendation generated by any agent.
    Enables learning from past decisions.
    """

    __tablename__ = "recommendation_history"

    id = Column(Integer, primary_key=True, index=True)
    agent_name = Column(String(100), nullable=False)       # "FinanceAgent" | "CEOAgent" etc.
    recommendation = Column(String(5000), nullable=False)
    reasoning = Column(String(5000), nullable=True)
    roi = Column(Float, default=0.0)                       # Estimated ROI %
    confidence = Column(Float, default=0.8)                # 0.0 → 1.0
    risk_level = Column(String(20), default="MEDIUM")      # LOW | MEDIUM | HIGH
    business_impact = Column(String(1000), nullable=True)
    affected_departments = Column(JSON, nullable=True)     # ["Finance", "Operations"]
    supporting_evidence = Column(JSON, nullable=True)      # List of data points
    status = Column(String(20), default="PENDING")         # PENDING | APPROVED | REJECTED | MODIFIED
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


class DecisionHistory(Base):
    """
    Tracks user actions taken on AI recommendations and observed business outcomes.
    This feedback loop improves future agent accuracy.
    """

    __tablename__ = "decision_history"

    id = Column(Integer, primary_key=True, index=True)
    recommendation_id = Column(Integer, nullable=True)     # FK to RecommendationHistory.id
    user_action = Column(String(20), nullable=False)       # APPROVED | REJECTED | MODIFIED
    modification_notes = Column(String(2000), nullable=True)
    business_outcome = Column(String(2000), nullable=True) # What actually happened
    outcome_revenue_impact = Column(Float, nullable=True)  # Measured $ impact
    feedback = Column(String(2000), nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
